# Fit_Transfrom using PCA..

In [1]:
# Import necessary library :
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.utils import resample

In [2]:
# create a data :
data  = make_classification(n_samples=1000, n_classes=2, random_state=23)

In [3]:
data

(array([[ 0.13232492,  0.33301267, -0.47925379, ..., -0.0372263 ,
         -0.55258414,  1.06965921],
        [ 1.89262246, -2.15538261, -0.39412158, ...,  1.69835282,
          0.09410361,  0.6390785 ],
        [ 0.50954567,  1.18669387,  0.95928732, ..., -0.54129521,
         -0.37482805, -2.18116821],
        ...,
        [-0.82153409,  0.61710388,  0.70239459, ..., -0.86275256,
         -0.56508439, -0.95485774],
        [ 0.61390331, -1.0616424 ,  0.88654963, ...,  0.99460724,
          0.17655184, -1.3007415 ],
        [-1.09364982, -0.25169781, -0.56959243, ..., -1.44205158,
         -0.86953376,  0.85196588]]),
 array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
   

In [4]:
# create a Dataframe :
df = pd.DataFrame(data[0], columns=[f"feature_{i}" for i in range(len(data[0][0]))])

In [5]:
df

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0     0.132325   0.333013  -0.479254   2.473071  -0.966725   0.493880   
1     1.892622  -2.155383  -0.394122   0.329241   0.390517  -1.404813   
2     0.509546   1.186694   0.959287   1.342229  -2.059967  -0.423093   
3     1.492415   1.043185   0.021732  -0.475620   1.041533  -0.127060   
4     0.485449  -0.190927  -0.800216  -0.108393  -1.856932   0.967366   
..         ...        ...        ...        ...        ...        ...   
995  -1.030286   1.078716   1.335299  -0.916411   0.474113   0.461051   
996  -1.288221   1.132577  -0.432915  -0.465875   0.011375  -0.038766   
997  -0.821534   0.617104   0.702395  -0.123714   1.089481   1.612707   
998   0.613903  -1.061642   0.886550  -0.125047   0.087675   1.218613   
999  -1.093650  -0.251698  -0.569592   1.793252   0.256770   0.417992   

     feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0    -0.247309   0.439594  -0.270557   1.506381    1.425326   -1.279706   
1    -1.215084  -0.310300   0.258698  -0.880988   -1.330219    0.217687   
2    -0.377241  -0.991911  -1.039653  -0.123355   -1.266389   -0.137042   
3     0.872141   0.017853   1.430772   0.194683   -1.085951   -1.780806   
4    -0.392703  -0.883419  -0.685578   0.777258   -0.806652    0.919138   
..         ...        ...        ...        ...         ...         ...   
995  -0.160864   1.828266   0.197674  -0.712917    0.238680   -1.245754   
996   0.323366   0.031350  -1.247558   0.924941    1.811024    0.376365   
997   1.165593   1.067099   0.593014   0.355985   -1.441057   -0.829265   
998  -1.115572   1.080081   0.697543  -0.830303    0.113996   -1.008243   
999   0.359678  -0.648519   0.167817  -1.059194   -2.627076    0.868639   

     feature_12  feature_13  feature_14  feature_15  feature_16  feature_17  \
0      1.825841   -0.764205   -0.104804    0.432687    2.300789   -0.037226   
1      0.270797    0.159286    0.938478    0.392049   -0.449108    1.698353   
2     -0.245330    0.356423    0.331232   -0.860039    1.462760   -0.541295   
3     -1.064841    0.484594    1.076660   -0.021658   -0.813202   -0.541893   
4     -0.157322   -1.676752    0.524323    0.809670   -1.121761   -0.329087   
..          ...         ...         ...         ...         ...         ...   
995   -0.911477    0.554306   -1.105743   -1.370168    0.307115   -0.339652   
996   -0.420680    1.219997    0.089217    0.410570   -0.136770   -1.322066   
997   -1.354036   -0.114174    1.019220   -0.726419    3.823261   -0.862753   
998   -0.546744   -0.502358   -1.631960   -0.902488   -0.437639    0.994607   
999    0.722315   -0.515020   -0.322334    0.577384   -0.337556   -1.442052   

     feature_18  feature_19  
0     -0.552584    1.069659  
1      0.094104    0.639079  
2     -0.374828   -2.181168  
3      1.127384   -0.034973  
4     -1.349292    1.206833  
..          ...         ...  
995    0.192328   -1.886998  
996   -1.683873    0.835263  
997   -0.565084   -0.954858  
998    0.176552   -1.300742  
999   -0.869534    0.851966  

[1000 rows x 20 columns]

In [6]:
# target col added in the dataframe :
df["target"] = data[1]

In [7]:
df.shape

(1000, 21)

In [8]:
df.head()

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0   0.132325   0.333013  -0.479254   2.473071  -0.966725   0.493880   
1   1.892622  -2.155383  -0.394122   0.329241   0.390517  -1.404813   
2   0.509546   1.186694   0.959287   1.342229  -2.059967  -0.423093   
3   1.492415   1.043185   0.021732  -0.475620   1.041533  -0.127060   
4   0.485449  -0.190927  -0.800216  -0.108393  -1.856932   0.967366   

   feature_6  feature_7  feature_8  feature_9  ...  feature_11  feature_12  \
0  -0.247309   0.439594  -0.270557   1.506381  ...   -1.279706    1.825841   
1  -1.215084  -0.310300   0.258698  -0.880988  ...    0.217687    0.270797   
2  -0.377241  -0.991911  -1.039653  -0.123355  ...   -0.137042   -0.245330   
3   0.872141   0.017853   1.430772   0.194683  ...   -1.780806   -1.064841   
4  -0.392703  -0.883419  -0.685578   0.777258  ...    0.919138   -0.157322   

   feature_13  feature_14  feature_15  feature_16  feature_17  feature_18  \
0   -0.764205   -0.104804    0.432687    2.300789   -0.037226   -0.552584   
1    0.159286    0.938478    0.392049   -0.449108    1.698353    0.094104   
2    0.356423    0.331232   -0.860039    1.462760   -0.541295   -0.374828   
3    0.484594    1.076660   -0.021658   -0.813202   -0.541893    1.127384   
4   -1.676752    0.524323    0.809670   -1.121761   -0.329087   -1.349292   

   feature_19  target  
0    1.069659       1  
1    0.639079       1  
2   -2.181168       0  
3   -0.034973       0  
4    1.206833       1  

[5 rows x 21 columns]

In [9]:
from sklearn.decomposition import PCA

In [10]:
# reduce a datsets into 5 components : resuce dimensions..
pca = PCA(n_components=5)

In [11]:
# Means trasform the data into 5 principle components :
new_df = pca.fit_transform(df.drop("target", axis=1))

In [12]:
new_df

array([[ 0.79701845,  1.34636196, -1.29800393, -0.59186014, -1.38503996],
       [ 0.88726987, -0.21393635,  0.94629552,  0.10752157,  0.2380177 ],
       [-1.83498295, -1.60415095,  0.94385299, -1.01374725, -0.50504837],
       ...,
       [-1.86184461,  0.19082033,  0.76284217,  0.20888766,  1.71871762],
       [-2.1790771 ,  0.23495948, -0.90723276,  0.31347229,  0.68636789],
       [ 1.31020062, -0.40593624, -0.00360492, -1.28093886,  0.12577481]])

In [13]:
# seperate the data into x and y :
x = new_df 
y = df["target"]

In [14]:
x

array([[ 0.79701845,  1.34636196, -1.29800393, -0.59186014, -1.38503996],
       [ 0.88726987, -0.21393635,  0.94629552,  0.10752157,  0.2380177 ],
       [-1.83498295, -1.60415095,  0.94385299, -1.01374725, -0.50504837],
       ...,
       [-1.86184461,  0.19082033,  0.76284217,  0.20888766,  1.71871762],
       [-2.1790771 ,  0.23495948, -0.90723276,  0.31347229,  0.68636789],
       [ 1.31020062, -0.40593624, -0.00360492, -1.28093886,  0.12577481]])

In [15]:
y

0      1
1      1
2      0
3      0
4      1
      ..
995    0
996    1
997    0
998    0
999    1
Name: target, Length: 1000, dtype: int32

In [16]:
# Generate a 1-dimensinally numpy array :
new = np.random.rand(20)

In [17]:
new

array([0.04707517, 0.99478936, 0.87134673, 0.3035705 , 0.18779253,
       0.37978205, 0.57685871, 0.33814343, 0.76848536, 0.78123711,
       0.09951589, 0.33888031, 0.00229771, 0.09005175, 0.71237017,
       0.22924986, 0.87051631, 0.63691799, 0.99038032, 0.11276393])

In [18]:
# Fitted PCA transform with new data points :
pca.transform([new])

C:\Users\kunal\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but PCA was fitted with feature names
  warnings.warn(


array([[-0.24022176,  0.44291325,  0.78913774,  0.25687675,  0.86314248]])

In [19]:
data[0]

array([[ 0.13232492,  0.33301267, -0.47925379, ..., -0.0372263 ,
        -0.55258414,  1.06965921],
       [ 1.89262246, -2.15538261, -0.39412158, ...,  1.69835282,
         0.09410361,  0.6390785 ],
       [ 0.50954567,  1.18669387,  0.95928732, ..., -0.54129521,
        -0.37482805, -2.18116821],
       ...,
       [-0.82153409,  0.61710388,  0.70239459, ..., -0.86275256,
        -0.56508439, -0.95485774],
       [ 0.61390331, -1.0616424 ,  0.88654963, ...,  0.99460724,
         0.17655184, -1.3007415 ],
       [-1.09364982, -0.25169781, -0.56959243, ..., -1.44205158,
        -0.86953376,  0.85196588]])

In [20]:
data[1]

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
# Split the data into training and testing :
X_train, X_test, y_train, y_test = train_test_split(df.drop("target", axis=1), df["target"], test_size=0.3, random_state=12)

In [23]:
pca = PCA(n_components=5)

x_train_pca = pca.fit_transform(X_train)
x_test_pca = pca.transform(X_test)

In [25]:
# Initilize the train LR model :
model = LogisticRegression()
model.fit(x_train_pca, y_train)

LogisticRegression()

In [26]:
# make pred on the test data :
y_pred = model.predict(x_test_pca)

In [31]:
# find accuracy score :
accuracy = accuracy_score(y_test, y_pred)
print("𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲 𝐒𝐜𝐨𝐫𝐞:", {accuracy})

𝐀𝐜𝐜𝐮𝐫𝐚𝐜𝐲 𝐒𝐜𝐨𝐫𝐞: {0.9066666666666666}


In [39]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧_𝐌𝐚𝐭𝐫𝐢𝐱: \n{conf_matrix}")

𝐂𝐨𝐧𝐟𝐮𝐬𝐢𝐨𝐧_𝐌𝐚𝐭𝐫𝐢𝐱: 
[[136  16]
 [ 12 136]]


In [41]:
class_report = classification_report(y_test, y_pred)
print(f"𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢o𝐧_𝐑𝐞𝐩𝐨𝐫𝐭: \n{class_report}")

𝐂𝐥𝐚𝐬𝐬𝐢𝐟𝐢𝐜𝐚𝐭𝐢o𝐧_𝐑𝐞𝐩𝐨𝐫𝐭: 
              precision    recall  f1-score   support

           0       0.92      0.89      0.91       152
           1       0.89      0.92      0.91       148

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300

